### ISSUE TITLE
Isn't this image missing 'gem install haml tilt'?

### ISSUE THREAD

**Issue by Batmat** [asciidoctor/docker-asciidoctor#11]
Hi,

Just tried to use that image to transform a .adoc to a deck.js presentation, and it didn't work at first shot.

After running:
    $ gem install haml tilt

And then, the transform runs fine.

Maybe I'm missing something else, 'cause I'm not at all Ruby/Gem savvy, but at least I hope this issue will help. That's also why I'm not (yet) filing a PR.

Once confirmed, I can sure do it.

Cheers!

**Comment by Batmat** [comment]
To work around that issue, I just created a new repo and a public image under: https://registry.hub.docker.com/u/batmat/asciidoctor-prez/

IMO, the official docker asciidoctor image should include all the packages (like tilt, haml above, but also for the other backends) so that one can use that image to generate their presentations based on asciidoctor's files.

**Comment by gscheibel** [comment]
Indeed, I've just included it.

Thanks for the feedback.
