### ISSUE TITLE
Makefile questions

### ISSUE THREAD

**Issue by lurch** [asciidoctor/docker-asciidoctor#110]
1. Why is `README.md` listed as a `.PHONY` dependency?

2. Would it make sense to have separate rules for updating README.md (I guess it could then be non-phony) and for pushing any README.md changes back into github (instead of having them combined into a single rule as they are now)

3. As `cache` is a directory, I think it should be listed as an [order-only dependency](https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html)? i.e. change
```
cache/pandoc-2.2-linux.tar.gz: cache
```
to
```
cache/pandoc-2.2-linux.tar.gz: | cache
```

4. Should the version of `pandoc` (currently 2.2) also be made into a Makefile variable, to make it easier to update? I'd be happy to put together a PR for this if you think it'd be useful.

**Comment by dduportal** [comment]
Hi @lurch , thanks for your patience while waiting for an answer to your questions:

> 1. Why is README.md listed as a .PHONY dependency?

Makefile target are not updated if the file exists. As the file `README.md` must be persisted and commited, as for today, for the Dockerhub to pick it, then it always exists. It means that any change in the `README.adoc` would not be picked as Make would consider the target already present.
What is expected, is that the target is run on each call and overwrite the existing file, e.g. no caching mechanism.

For sure, my knowledge of `Makefile` is far from complete: if I missed anything in the PHONY targets usage here, feel free to point it to me :)

> 2. Would it make sense to have separate rules for updating README.md (I guess it could then be non-phony) and for pushing any README.md changes back into github (instead of having them combined into a single rule as they are now)

Yes, it would make sense, as the current "monolithic" rule also makes sense. It's a tradeoff to avoid a too much complex `Makefile` with tons of rules. What would be the goal (and end-user value) in your proposal of splitting it? (I'm not pro neither against: if it serves the end user, let's do it).

> 3. As cache is a directory, I think it should be listed as an order-only dependency?

Good point, I did not know this Make dependency pattern, for sure this should be improved in our makefile! Are you ready to contribute on this?

> 4. Should the version of pandoc (currently 2.2) also be made into a Makefile variable, to make it easier to update? I'd be happy to put together a PR for this if you think it'd be useful.

Same here: you can create another PR for this! Thanks !

**Comment by dduportal** [comment]
Closing this issue as it seems to have been answered. Thanks for reporting and contributing to improve the quality of the project. Of course, feel free to reopen if your problem is not solved.
