### ISSUE TITLE
Link Asciidoctor Github Organization with DockerHub

### ISSUE THREAD

**Issue by dduportal** [asciidoctor/docker-asciidoctor#115]
Hi @mojavelinux ,

as noticed by @juracy in <https://github.com/asciidoctor/docker-asciidoctor/pull/114#issuecomment-548761977>, the Docker Hub auto builder is building anymore.

After a quick check, it appears that the Docker Hub "asciidoctor" organisation is not linked to the Github organisation `asciidoctor` (from <https://cloud.docker.com/u/asciidoctor/settings/?github-link=1> -> Select "Linked Accounts" on the left menu):

<img width="966" alt="Screenshot 2019-11-02 at 10 16 52" src="https://user-images.githubusercontent.com/1522731/68068859-f2447480-fd59-11e9-8d5a-213f5422efe8.png">

An admin of the Github org. is required so here si the issue for you :)

It looks like that Docker recommends to setup a "service user" for such cases: https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds .

**Comment by mojavelinux** [comment]
I have made this link. We already have a service user named asciidoctor-docbot, who is a member of the Agents team. I have made the link using that account and also add the Agents team to this repository.

If there's anything else you need, just let me know.

**Comment by dduportal** [comment]
Confirmed that it works: @mojavelinux fixed the account linking, and new master build had been triggered: https://hub.docker.com/repository/registry-1.docker.io/asciidoctor/docker-asciidoctor/builds/6343fdcd-ec61-4558-a512-536d226ddad6 .

It built successfully, meaning the Docker image with the tag `latest` is in sync with the master branch (again):

```bash
docker pull asciidoctor/docker-asciidoctor && docker run --rm -t asciidoctor/docker-asciidoctor asciidoctor-pdf --version
Using default tag: latest
latest: Pulling from asciidoctor/docker-asciidoctor
89d9c30c1d48: Already exists 
76434bd719a2: Pull complete 
e1bab9e0dee8: Pull complete 
2a42d81e75b3: Pull complete 
92642922b6d9: Pull complete 
Digest: sha256:eb60a6a96c34498387cc75f615e8032e2f8cbc7a9310589880d772d90a12cacf
Status: Downloaded newer image for asciidoctor/docker-asciidoctor:latest
docker.io/asciidoctor/docker-asciidoctor:latest
Asciidoctor PDF 1.5.0.beta.7 using Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
```

Thanks all!
