### ISSUE TITLE
asciidoctor: WARNING: conversion missing in backend pdf for stem

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/docker-asciidoctor#118]
Get this error when using 0.3.1 of asciidoctor-mathematical and running asciidoc from docker image (https://github.com/asciidoctor/docker-asciidoctor/blob/master/Dockerfile):

```
bash-5.0# asciidoctor-pdf --trace -d book -r asciidoctor-diagram -r asciidoctor-mathematical chap02.adoc
asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem
asciidoctor: WARNING: conversion missing in backend pdf for stem
```

The math content does not render in the pdf. Here is example math content:

```
[stem]
++++
sig = enc(H(D), s)
++++
```

I am not sure if the problem is with `asciidoctor-mathematical` or with `docker-asciidoctor`

**Comment by mojavelinux** [comment]
You are missing the required `stem` attribute to activate stem support.

```
:stem: latexmath

[stem]
++++
sig = enc(H(D), s)
++++
```

**Comment by siddjain** [comment]
Thanks. That works. I did have
```
 :stem:
```
adding `latexmath` to it did the trick.
