### ISSUE TITLE
asciidoctor-pdf does not correctly render asciimath in the sample-with-asciimath.pdf

### ISSUE THREAD

**Issue by osipov** [asciidoctor/docker-asciidoctor#142]
Please take a look at the attached output of using asciidoctor-pdf by following the instructions in this repo and the Docker image asciidoctor/docker-asciidoctor:latest

[sample-with-asciimath.pdf](https://github.com/asciidoctor/docker-asciidoctor/files/4382439/sample-with-asciimath.pdf)

**Comment by mojavelinux** [comment]
It appears you have not activated the asciidoctor-mathematical extension. Can you please document the exact command you executed?

**Comment by osipov** [comment]
I launch /bin/bash in the docker container and connected to it using 

```docker run -it -v <mydir>/manuscript:/manuscript asciidoctor/docker-asciidoctor /bin/bash```

then, inside the Docker container's bash shell

``` 
cd manuscript
asciidoctor-pdf -r asciidoctor-mathematical sample-with-asciimath.adoc 
```

which produced a pdf file ```/manuscript/sample-with-asciimath.pdf``` attached to this issue.

**Comment by mojavelinux** [comment]
Can you provide the source of the AsciiDoc file?

>

**Comment by osipov** [comment]
Sure thing. It was right from the test suite: https://github.com/asciidoctor/docker-asciidoctor/blob/master/tests/fixtures/sample-with-asciimath.adoc

**Comment by mojavelinux** [comment]
You're correct, asciidoctor-mathematical only does latex, not asciimath.

**Comment by osipov** [comment]
OK, I just reproduced the problem without asciidoc-mathematical by using 

```bash
cd /manuscript
asciidoctor-pdf sample-with-asciimath.adoc 
```

**Comment by mojavelinux** [comment]
It's doing what's expected. When the stem isn't supported (either because it's AsciiMath or asciidoctor-mathematical is not loaded), then it presents the equation as a listing block.

**Comment by osipov** [comment]
Sorry, I'm totally confused now. The README.md here: https://github.com/asciidoctor/docker-asciidoctor makes the claim that asciimath is supported. The same repo contains tests for asciimath and latexmath. However when I try to render asciimath content as pdf, the equation is rendered as text instead of as math. 

Are you suggesting that this is the expected behavior for the docker container in the repo? This doesn't sound right, so are there different instructions for using the docker container to render asciimath? Thank you!

**Comment by mojavelinux** [comment]
It's supported, just not for PDF (as it has never been supported for PDF). It's supported for HTML and DocBook.

**Comment by dduportal** [comment]
Unless I'm mistaken (feel free to tell it there :) ), this issue underlines that a documentation addendum is needed.
What do you think @osipov , if we state clearly in the readme that only HTML and docbook are supported for asciimath? Do you feel that this addendum avoid other people to fell in this dead end?

**Comment by slonopotamus** [comment]
Asciidoctor EPUB3 also supports AsciiMath starting with 1.5.0.alpha.18 (released today).

**Comment by mojavelinux** [comment]
As of version 0.3.4 of the asciidoctor-mathematical gem, AsciiMath is now supported. So if the Docker image is upgraded to asciidoctor-mathematical 0.3.4, this bug can be resolved. https://rubygems.org/gems/asciidoctor-mathematical

NOTE: There's still one outstanding bug (https://github.com/asciidoctor/asciidoctor-mathematical/issues/87), but it's possible to work around it.

**Comment by dduportal** [comment]
Hello 👋 

The Docker image is using asciidoctor-mathematical version `0.3.5` since the recent [`1.3.1`](https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.3.1) release.

It should solve the 2 issues, unless I misunderstood something.

Thanks for reporting and contributing to the project's quality! Closing this issue, feel free to reopen it with a comment if it does not solve your problem of course.
