### ISSUE TITLE
Switching to MathJax?

### ISSUE THREAD

**Issue by siddjain** [asciidoctor/docker-asciidoctor#146]
I have read at some places at MathJax is supposedly better than asciidoc-mathematical. Is there any plan to switch docker-asciidoctor from asciidoc-mathematical to MathJax? Any ticket or task I can subscribe to, to get the status?

**Comment by mojavelinux** [comment]
You're comparing apples to oranges. asciidoctor-mathematical is used where MathJax cannot be used. Specifically, it's used in PDF generation, where a client-side JavaScript library is not applicable.

The typically workflow is using MathJax for HTML output an asciioctor-mathematical for PDF output (and EPUB3 as well, though technically it could support MathJax on certain readers).

Yes, MathJax is far superior. But that's not the point.

**Comment by dduportal** [comment]
Closing this issue as there was no answer back from author.

Please feel free to reopen if you have a use case you can provide or if the answer from @mojavelinux is not exaplaining enough. Thanks a lot !
