### ISSUE TITLE
Integrate asciidoctor-epub3

### ISSUE THREAD

**Issue by mbalmer** [asciidoctor/docker-asciidoctor#147]
I would love to see asciidoctor-epub3 being integrated in this otherwise very useful docker image.

**Comment by mojavelinux** [comment]
asciidoctor-epub3 is already in this image.

https://github.com/asciidoctor/docker-asciidoctor/blob/master/Dockerfile#L57

Have you tried it?

**Comment by mbalmer** [comment]
Perfect then!

I used the version from docker hub, I did not build it from the Dockerfile.  I will retry, but in any case this issue can be closed.

Thanks for the good work!

- Marc

**Comment by mbalmer** [comment]
It works as advertised ;)
