### ISSUE TITLE
Is asciidoctor-diagram integrated, or, will it ever be?

### ISSUE THREAD

**Issue by mbalmer** [asciidoctor/docker-asciidoctor#148]
Are there plans to integrate asciidoctor-diagram with this docker image?  Or is it already integrated?

**Comment by mojavelinux** [comment]
Asciidoctor Diagram is already included in the Docker image. Please consult the README and/or Dockerfile to learn what is integrated.

* https://github.com/asciidoctor/docker-asciidoctor#the-environment
* https://github.com/asciidoctor/docker-asciidoctor/blob/master/Dockerfile

In the future, please direct questions to the gitter channel https://gitter.im/asciidoctor/asciidoctor or discussion list https://discuss.asciidoctor.org
