### ISSUE TITLE
provide Docker image tags for minor and major releases (coarser matching)

### ISSUE THREAD

**Issue by das-g** [asciidoctor/docker-asciidoctor#150]
Additionally to the tags with the full patch version `x.y.z`, provide tags that allow to be on the latest release of a certain minor version `x.y` and tags that allow to be on the latest release of a certain major version `x`.

So
Tag `1.1` should point to the same image as the latest `1.1.*` tag (currently `1.1.0`, later maybe `1.1.15`, but never `1.2.0`).
Tag `1` should point to the same image as the latest `1.*.*` tag (currently `1.1.0`, later maybe `1.5.42`, but never `2.0.0`).

Off course this is only really useful if this project uses [semantic versioning](https://semver.org/). But although I didn't see it declared explicitly, I assume that's the case, isn't it?

**Comment by dduportal** [comment]
Hello @das-g , thanks for opening this issue! The use case is described clearly, and it is a legit request.
We'll see how to implement this behavior, but if you feel ready, do not hesitate to open a PR with a proposal (even as a "draft"), as any help is welcome.

**Comment by das-g** [comment]
> Hello @das-g , thanks for opening this issue! The use case is described clearly, and it is a legit request.
> We'll see how to implement this behavior, [...]

Thanks!

I think this is best done [through the autobuild configuration on dockerhub](https://stackoverflow.com/a/44796846/674064).

| Type   | Name                                | Dockerfile Location | Docker Tag Name  |
|--------|-------------------------------------|---------------------|------------------|
| Branch | `master`                            | `/`                 | `latest`         |
| Tag    | `/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/` | `/`                 | `{\1}`           |
| Tag    | `/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/` | `/`                 | `{\1}.{\2}`      |
| Tag    | `/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/` | `/`                 | `{\1}.{\2}.{\3}` |

That would have to be done by someone with configuration access to https://github.com/asciidoctor/docker-asciidoctor.

> [...] but if you feel ready, do not hesitate to open a PR with a proposal (even as a "draft"), as any help is welcome.

Whether there's any way to accomplish the same through a PR (i.e., by changing the content of files in this repo), I don't know.

**Comment by dduportal** [comment]
Thanks a lot @das-g for these insights.

The release 1.2.0 had been published with this new tags, and the previous tagged version are currently being rebuilt: https://hub.docker.com/repository/docker/asciidoctor/docker-asciidoctor/tags?page=1
