### ISSUE TITLE
License

### ISSUE THREAD

**Issue by clbarnes** [asciidoctor/docker-asciidoctor#158]
I couldn't see an obvious license for this repository. Is it open source?

**Comment by mojavelinux** [comment]
All projects in the asciidoctor organization are open source. The absence of the license file in this repository appears to be an oversight. By default, Asciidoctor projects uses the MIT license, but I'll let @dduportal decide which license fits best for this purpose.

**Comment by dduportal** [comment]
Sounds good, thanks for pointing it out!

MIT looks good as it's already used by Asciidoctor. 

I might be wrong, but as far as I understand the licensing, since we only use binaries of dependencies, the MIT license should suffice without breaching intellectual property of dependencies?

**Comment by mojavelinux** [comment]
> as far as I understand the licensing, since we only use binaries of dependencies, the MIT license should suffice without breaching intellectual property of dependencies?

That's correct. The license applies to this work, not the work on which the container is run (Alpine) or requests (packages). You are essentially licensing the Dockerfile and built itself.
