### ISSUE TITLE
doc: how to apply my own theme?

### ISSUE THREAD

**Issue by goern** [asciidoctor/docker-asciidoctor#16]
using something like `docker run -it --rm -v $PWD:/documents/ asciidoctor/docker-asciidoctor asciidoctor-pdf -r asciidoctor-diagram mydoc.asciidoc` will result in a wonderful PDF. But how do I apply a theme?

My own approach (https://goern.github.io/asciinurse/#_i_need_a_pdf_please) is to include the theme into the docker image ... https://github.com/goern/asciinurse/blob/master/Dockerfile#L38

**Comment by gscheibel** [comment]
Hello,

The easiest way is to use the container as a shell:

$ docker run -it -v /your/path/:/document/ asciidoctor/docker-asciidoctor

Then once in the container you can use the shell as if you were on your
host machine.

$ asciidoctor-pdf -r asciidoctor-diagram mydoc.asciidoc

I assume you want to use pdf theme right ? In this case if you can put your
theme next to your document and 'pdf-styledir' attributes (cf:
https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc#applying-your-theme)
you will be able to apply the theme.

Let me know if you have any other question or idea to improve the container.

Cheers,
Guillaume

**Comment by goern** [comment]
Wow, cool, seems to do what I wanted to do :) thx

**Comment by goern** [comment]
So, I you could include that guard pattern I use in asciinurse? Than I can shut down my project.

**Comment by gscheibel** [comment]
What do you mean by "guard pattern" ?
