### ISSUE TITLE
Migrate away from travis-ci.org

### ISSUE THREAD

**Issue by slonopotamus** [asciidoctor/docker-asciidoctor#168]
travis-ci.**org** is going to be shut down on **December, 31**:

https://docs.travis-ci.com/user/migrate/open-source-repository-migration#frequently-asked-questions

> Q. When will the migration from travis-ci.org to travis-ci.com be completed?
> A. In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

> Q. What will happen to travis-ci.org after December 31st, 2020?
> A. Travis-ci.org will be switched to a read-only platform, allowing you to see your jobs build history from all repositories previously connected to travis-ci.org.

Also, note that travis-ci.**com**, while being the most logical place to move to, has **build time limits** for public repositories:

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).

Most of Asciidoctor ecosystem has already moved to GitHub Actions.

**Comment by dduportal** [comment]
Hi @slonopotamus , really good proposal, as the Travis CI build are already slow, and we should follow the rest of the asciidocor project.

FWIW Let's go on this topic! I plan to work on this after the 18th of December if no contribution had been done: it means that any contribution is welcome :)
