### ISSUE TITLE
ditaa diagrams in PDF

### ISSUE THREAD

**Issue by goern** [asciidoctor/docker-asciidoctor#17]
I have seen that my ditaa diagrams seem to be like 50% of the page in my PDF, is that a default value somewhere? The code I use is something like:
```
.ACME Corp Org Chart
[ditaa]
----
                                                     +----------------+
                                                     |                |
                                                     |  CEO Office    |
                                                     |                |
                                                     +-------+--------+
----
```

**Comment by gscheibel** [comment]
50% height ?

I've tried with a test doc (with the diagram you posted) and the result is
correct.

**Comment by goern** [comment]
oh, sorry, no.. 50% width

**Comment by gscheibel** [comment]
The diagram is only taking half of the page width and you would like it to
use 100% right ?

**Comment by gscheibel** [comment]
Therefore, it concerns asciidoctor-pdf more than the docker container I
suggest you open or comment (if already exists) an issue on this page:

https://github.com/asciidoctor/asciidoctor-pdf/issues

And we'll have a look at it.

**Comment by goern** [comment]
ja, thanks!
