### ISSUE TITLE
Inline stem not rendered in 'latest' container

### ISSUE THREAD

**Issue by cbachhuber** [asciidoctor/docker-asciidoctor#179]
Given `file.adoc` with content

```adoc
:stem: latexmath 

= Math to PDF render failure

In container `asciidoctor/docker-asciidoctor:latest`, this inline stem:[\sqrt{4} = 2], is not rendered, but a stem block

[stem]
++++
\sqrt{4} = 2
++++

is rendered correctly.

This is not the case in `asciidoctor/docker-asciidoctor:1.2`
```

is rendered as expected ([file_1_2.pdf](https://github.com/asciidoctor/docker-asciidoctor/files/5897660/file_1_2.pdf)) in `asciidoctor/docker-asciidoctor:1.2` using 

```shell
docker run -it -v /home/chris/my_folder/:/documents asciidoctor/docker-asciidoctor:1.2
bash-5.0# asciidoctor-pdf -r asciidoctor-mathematical file.adoc
```

In `asciidoctor/docker-asciidoctor:latest`, inline stem content is not rendered ([file_latest.pdf](https://github.com/asciidoctor/docker-asciidoctor/files/5897662/file_latest.pdf)), however.

```shell
docker run -it -v /home/chris/my_folder/:/documents asciidoctor/docker-asciidoctor:latest
bash-5.0# asciidoctor-pdf -r asciidoctor-mathematical file.adoc
```

I expect `latest` to provide a superset of `1.2`'s features. Is this expectation wrong?

**Comment by mojavelinux** [comment]
What you're observing is a regression that affected asciidoctor-mathematical 0.3.4 (which is included in the latest tag). The solution is to upgrade to 0.3.5. Here's the PR that fixed the problem: https://github.com/asciidoctor/asciidoctor-mathematical/pull/92

**Comment by cbachhuber** [comment]
Got it, thank you for the info! When will the latest tag include asciidoctor-mathematical 0.3.5?

**Comment by dduportal** [comment]
This is correct: the `latest` tag is always up to date with the HEAD of the principal (`main`) branch, and is in sync with the image's tag 1.3.0 at the date of this comment. The release note of `asciidcotor/docker-asciidoctor:1.3.0` can be found in GitHub: https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.3.0 , and it confirm that the current `asciidoctor-mathematical` version is `0.3.4` (as per https://github.com/asciidoctor/docker-asciidoctor/pull/165).


> When will the latest tag include asciidoctor-mathematical 0.3.5?

There is no pull request on this topic yet. Would you be willing to help us by contributing (following the changes from #165 as base example)? As soon as your PR is merged, the `latest` image would carry your change.
