### ISSUE TITLE
Upgrade to latest asciidoctor-diagram

### ISSUE THREAD

**Issue by jtama** [asciidoctor/docker-asciidoctor#207]
Hi,
This relates to https://github.com/asciidoctor/asciidoctor-diagram/issues/357. Once it's released can you please update to latest version ?
This allow full use of plantuml std libraries.

Thanks.

**Comment by dduportal** [comment]
Hello @jtama , as soon as the daily job using updatecli will be executed, it should trigger a PR if it detects a new release as per https://github.com/asciidoctor/docker-asciidoctor/blob/main/updatecli/updatecli.d/asciidoctor-diagram.yml . Let's see if the process works as expected.

**Comment by dduportal** [comment]
Quick update: alas asciidoctor-diagram had not been released yet (at least not since the 3rd of April). Wait & see.

**Comment by dduportal** [comment]
Asciidocotr-diagram had been released 2 days ago, the autoamtic update process picked it yesterday: it has been released today with the version 1.11.0 of the container.

It's already available in the Docker Hub: https://hub.docker.com/r/asciidoctor/docker-asciidoctor/tags?page=1&ordering=last_updated&name=1.11
