### ISSUE TITLE
Tag 1.8.0 not on hub.docker.com?

### ISSUE THREAD

**Issue by vojkog** [asciidoctor/docker-asciidoctor#212]
Should the tag **1.8.0** be available here?   https://hub.docker.com/r/asciidoctor/docker-asciidoctor/tags?page=1&ordering=last_updated

**Comment by dduportal** [comment]
Hello @vojkog , thanks for reporting.

You are correct, the tag should be deployed to the DockerHub but it isn't :(

There is a succeesfull build associated to the tag: https://github.com/asciidoctor/docker-asciidoctor/runs/2924275047?check_suite_focus=true , I'm currently checking why the image was not pushed.

For sure it's a bug in the GH action's workflow.

**Comment by dduportal** [comment]
Ok, a hotfix has been pushed and the tag have been changed.

A new build is triggered that should have the correct image name: https://github.com/asciidoctor/docker-asciidoctor/actions/runs/1047857586/workflow#L64

**Comment by dduportal** [comment]
Tag is now present on the DockerHub 🥳
