### ISSUE TITLE
Where to send informations about vulnerabilities?

### ISSUE THREAD

**Issue by burghard-britzke-drv** [asciidoctor/docker-asciidoctor#219]
The possible taget for infos about vulnerabilities is unknown for this project. There is an empty security advisory and no security policy for this project. How should I inform the Project about such vulnerabilities?

**Comment by dduportal** [comment]
Hello @burghard-britzke-drv , there isn't really any procedure for this repository, so I defer to @mojavelinux to answer for this one (once I'll know, I'll create a security policy here).

Ideally, contacting both @mojavelinux and I privately could be a great start

**Comment by mojavelinux** [comment]
I started a thread in the `#dev` stream of the community chat to discuss. Please follow-up there. I don't think an issue in this repository is the right scope for this discussion.

**Comment by dduportal** [comment]
Thanks a lot @mojavelinux . Closing the issue as per your message. @burghard-britzke-drv could you join our channel in #dev (in gitter)?
