### ISSUE TITLE
install asciidoctor-mathematical

### ISSUE THREAD

**Issue by JmyL** [asciidoctor/docker-asciidoctor#22]
I need it when building doc with stem on asciidoctor-pdf.

**Comment by gscheibel** [comment]
Hi @JmyL ,
Do you have a document I could use to double check it has been done correctly?

**Comment by gscheibel** [comment]
BTW, the only `asciidoctor-mathematical` I've seen is: https://github.com/tstumm/asciidoctor-mathematical
Is it what you are talking about or do you have something else in mind?

**Comment by JmyL** [comment]
Thx for reviewing, @gscheibel !
That's what I've used. It was mensioned on here: https://github.com/asciidoctor/asciidoctor-pdf/issues/45

**Comment by JmyL** [comment]
And there's another solution "MathoidTreeprocessor", at https://github.com/asciidoctor/asciidoctor-extensions-lab

**Comment by JmyL** [comment]
I've installed make cmake spawn bzip2-devel cmake gcc-c++ glib* cairo-devel pango-devel gdk-pixbuf2-devel libxml2-devel bison flex libffi-devel and `gem install asciidoctor-mathematical` was succeeded.

But when converting asciidoc doc with `-r asciidoctor-mathematical`, asciidoctor is looking for `liblasem.so`.

@gscheibel, Do you know how to install lasem on fedora?

**Comment by JmyL** [comment]
I finally succeeded... but math image is too small when using asciidoctor-mathematical, it is far better when using mathematical-treeprocessor.rb on asciidoctor-extensions-lab.

I'm now trying to find out how to convert asciimath also ;) Here's a [link](https://github.com/tstumm/asciidoctor-mathematical/issues/6).

Here's a [Dockerfile](https://gist.github.com/JmyL/c0055dba6b370528f560) I've tried.

**Comment by tstumm** [comment]
If I remember rightly, adding
`:mathematical-format: svg`
at the top of your document should render the graphics as SVGs (which are bigger as they are not scaled down).

**Comment by JmyL** [comment]
Exactly write ;)

**Comment by bramgosseye** [comment]
@JmyL How dit you solve the problem with `liblasem.so`?

When I use asciidoctor-mathematical, I get the following erorr:

`/usr/local/share/ruby/site_ruby/rubygems/core_ext/kernel_require.rb:55:in `require': liblasem.so: cannot open shared object file: No such file or directory - /home/vagrant/.gem/ruby/gems/mathematical-1.6.7/ext/mathematical/mathematical.so (LoadError)`

**Comment by dduportal** [comment]
Hello @JmyL , with the today's update, `asciidoctor-mathematical` is now installed. 
Can you try with the latest image built today to confirm if your use-case is working?

Thanks in advance!

**Comment by JmyL** [comment]
Hello @dduportal ! I'll tell you after try the latest image.

Thx!

**Comment by JmyL** [comment]
@dduportal Unfortunately, recently I do not use ``asciidoctor-mathematical`` because I use wkhtmltopdf to render math equations.

I'll try to use [``asciidoctor-mathematical`` and ``asciidoctor-pdf`` combination](https://github.com/asciidoctor/asciidoctor-pdf#asciidoctor-mathematical).

**Comment by dduportal** [comment]
Hello @JmyL, thank you for the feedback.

I will close this issue since it is solved (theoretically :) ).

Please, feel free to reopen if you see any issue or concern with the usage of asciidoctor-mathematical.

Thanks for taking time to report!
