### ISSUE TITLE
Add support for BPMN diagrams

### ISSUE THREAD

**Issue by gautaz** [asciidoctor/docker-asciidoctor#320]
Hello,

Looking at [the documentation](https://docs.asciidoctor.org/diagram-extension/latest/#creating-a-diagram), it seems that BPMN diagrams are supported by `asciidoctor-pdf`.

However, when trying to generate a PDF file from an asciidoc file containing a BPMN diagram, the container issues the following error:
```
asciidoctor: ERROR: diagrams/test.bpmn: line 0: Failed to generate image: Could not find the 'bpmn-js' executable in PATH; add it to the PATH or specify its location using the 'bpmn-js' document attribute
```

**Comment by gautaz** [comment]
I've managed to get a little further by using `-r asciidoctor-kroki` instead of `-r asciidoctor-diagram` but it fails with the following warning:

```
asciidoctor: WARNING: could not retrieve remote image: https://kroki.io/bpmn/svg/<...very long...> 414 URI Too Long
```

I guess the diagram sources are too long (BPMN = XML) to be passed as a URI.

**Comment by barthel** [comment]
I'm building a full blown Asciidoctor Container Image with all Asciidoctor Diagrams extensions.
BPMS is already implemented.
Give it a try.

Github: https://github.com/barthel/docker-asciidoctor
Docker Hub: https://hub.docker.com/r/uwebarthel/asciidoctor

**Comment by gautaz** [comment]
Spring cleaning time!
There is no need to keep this issue anymore, feel free to reopen a new one if needed.
