### ISSUE TITLE
Add label org.opencontainers.image.source="https://github.com/asciidoctor/docker-asciidoctor"

### ISSUE THREAD

**Issue by marwin1991** [asciidoctor/docker-asciidoctor#325]
Hello, for tools like renovate it is important to have define label `org.opencontainers.image.source`

So can we add label org.opencontainers.image.source="https://github.com/asciidoctor/docker-asciidoctor" to DOCKERFILE ?

Base on this label, renovate will provide information about changes.

- https://docs.renovatebot.com/modules/datasource/docker/
- https://github.com/opencontainers/image-spec/blob/main/annotations.md

**Comment by marwin1991** [comment]
I can create pull request with this change :)

**Comment by dduportal** [comment]
Hi @marwin1991 , thanks for raising this issue. You are welcome to open a pull request: I'll take care of reviewing/merging/deploying it, as your proposal absolutly makes sense!

**Comment by marwin1991** [comment]
@dduportal 
If you will have some free time https://github.com/asciidoctor/docker-asciidoctor/pull/329

**Comment by dduportal** [comment]
Thanks @marwin1991 !
