### ISSUE TITLE
Full description rendering issue on docker hub

### ISSUE THREAD

**Issue by tbreuss** [asciidoctor/docker-asciidoctor#42]
The full description at https://hub.docker.com/r/asciidoctor/docker-asciidoctor/ is not rendered at all (see attached screenshot).

![docker-hub-asciidoctor](https://user-images.githubusercontent.com/1334161/27251098-d3aa5722-533f-11e7-8349-22fd95af181e.png)

I suppose the reason is the lack of asciidoc support at docker hub. If this is the case it would be better to write the README.adoc in markdown syntax?

**Comment by mojavelinux** [comment]
If the README is simple enough, one solution is to use the Markdown-esque syntax in Asciidoctor.

    # Document Title

    ```bash
    docker run
    ```

The other option is to simply convert the content to Markdown and paste it into the field on DockerHub. We have some scripts floating around to convert from AsciiDoc to Markdown (to automate it), but the document is small enough that doing it manually isn't too bad for now.

**Comment by tbreuss** [comment]
Another option would be: Instead of using an README.adoc (https://github.com/asciidoctor/docker-asciidoctor/blob/master/README.adoc <https://github.com/asciidoctor/docker-asciidoctor/blob/master/README.adoc>) you could simply use a README.md. This would ensure that the rendering of the README is correctly done both on Github and Docker Hub.

**Comment by mojavelinux** [comment]
Sorry, but I believe that would go against the principles and spirit of
this project. I'm okay with down converting for rendering purposes, but the
canonical document should be maintained in AsciiDoc IMO.

**Comment by tbreuss** [comment]
I fully understand and you are right.

What originally bothered me was to use a Docker Image that is used to render text into a nice looking document and the description on Docker Hub is in fact not rendered and nice-looking… So, this is more a „marketing“ thing.

Last option: Maybe we should try to convince Docker Hub to support Asciidoc too?

**Comment by mojavelinux** [comment]
> this is more a „marketing“ thing.

100% with you.

But I think you're missing the simple solution. We can simply down convert and paste into the description box. Let's not make this more complicated than it is. (We can then follow-up with a script to update it once that step is taken).

p.s. Here's a crude script to do this conversion. https://github.com/asciidoctor/asciidoctor.js/blob/master/npm/prepublish.js.

**Comment by tbreuss** [comment]
👍 sounds good

**Comment by mojavelinux** [comment]
Actually, there's a far easier way.

```
asciidoctor-dev -b docbook -o - README.adoc | \
pandoc --wrap=preserve -t markdown_github -f docbook - > README.md
```

DocBook serves as an excellent interchange format.

**Comment by dduportal** [comment]
Hello @tbreuss and @mojavelinux !

I have put a proposal of PR based on @mojavelinux instructions, which orchestrate this README generation.

What do you think?

**Comment by mojavelinux** [comment]
:+1:
