### ISSUE TITLE
Tag 1.68.0 missing from Docker Hub

### ISSUE THREAD

**Issue by tbroyer** [asciidoctor/docker-asciidoctor#439]
As of now, tag `latest` has been updated, but no `1.68.0` tag has been created: https://hub.docker.com/r/asciidoctor/docker-asciidoctor/tags

![Screenshot of the Docker Hub page](https://github.com/asciidoctor/docker-asciidoctor/assets/173813/17c542e2-61e7-4763-a268-6584a576ee1d)

**Comment by dduportal** [comment]
Thanks for reporting!

It looks like I broke the delivery system with https://github.com/asciidoctor/docker-asciidoctor/pull/434: `latest` is deployed as expected from the `main` branch but tags are not picked up (my `if` expression is incomplete).

Working on a patch right now, I'll republish the `1.68.0` tag

**Comment by dduportal** [comment]
Just pushed an hotfix: https://github.com/asciidoctor/docker-asciidoctor/commit/d6f7ca94aef83f598029df416e522b1d44c27d86 Let's see the result!

**Comment by dduportal** [comment]
Finally images are deployed!

Sorry for the inconvenience I caused with #434.

I had to update the (quite old) conditional syntax and fix my mistakes with the following hotfixes (not mentioned in release not as they do not cover the content of the image itself. Anyone who want them please shoot and I'll add them no problem: it is just it should not bother end users from my PoV but no strong opinion):

- https://github.com/asciidoctor/docker-asciidoctor/commit/d6f7ca94aef83f598029df416e522b1d44c27d86
- https://github.com/asciidoctor/docker-asciidoctor/commit/2bd66435c0083a4c3566091401e70913d879f2cd
- https://github.com/asciidoctor/docker-asciidoctor/commit/8962b3ad7517ebd33a4799167b932dd34830146c

<img width="1332" alt="Capture d’écran 2024-03-12 à 20 00 01" src="https://github.com/asciidoctor/docker-asciidoctor/assets/1522731/1d2146ef-f7b3-44be-a921-6d035898bc32">

**Comment by dduportal** [comment]
And release is republished: https://github.com/asciidoctor/docker-asciidoctor/releases/tag/1.68.0


Many thanks @tbroyer for reporting! I'm closing, feel free to reopen if needed
