### ISSUE TITLE
asciidoctor-diagram doesn't work on alpine based image

### ISSUE THREAD

**Issue by ryosms** [asciidoctor/docker-asciidoctor#44]
with this sample.adoc file:

```sample.adoc
= sample

[plantuml,sample-diagram,svg]
----
class Sample {
}
----
```

I try below, and I've got error

```bash
$ docker run -it --rm -v $(pwd)/documents:/documents asciidoctor/docker-asciidoctor
bash-4.3# asciidoctor -r asciidoctor-diagram sample.adoc

asciidoctor-diagram: ERROR: Failed to generate image: Could not find Java executable
```

**Comment by mojavelinux** [comment]
I think there was a misunderstanding the the JDK was only needed for fopub, which was removed from the image. (See https://github.com/asciidoctor/docker-asciidoctor/pull/39#issuecomment-334164763) However, the JDK is definitely needed for asciidoctor-diagram as several of the tools use it.

**Comment by wimdeblauwe** [comment]
I would love to see this fixed as well. The main reason for running the document creation in docker is to avoid people having to install all kind of things to make the diagrams work.

**Comment by dduportal** [comment]
Hello!

Thank you for writing this issue!

As @mojavelinux stated, it was a misunderstanding from me. I apologize for the inconvenience.

Expect a fix to be proposed this weekend, with this issue's reproduction case as test for non-reproduction in the future.

**Comment by dduportal** [comment]
Hello @ryosms, 

The "latest" Docker Image has been rebuilt with the support (back) of asciidoctor-diagram.

You can get it v-by re-pulling the image with the following command: 

```bash
docker pull asciidoctor/docker-asciidoctor
```

Feel free to re-open this issue if you face any issue or if you are not happy with the result.

Thanks for taking time for reporting!

**Comment by aowss** [comment]
i think that problem has been re-introduced in 1.17

**Comment by dduportal** [comment]
> i think that problem has been re-introduced in 1.17

Hello @aowss ! Thanks for reporting!
Could you share a reproduction case please and reopen the issue please? 

Since 1.17 has an updated JDK to a major version, it might have broke something. Alas the test harnes did not show anything: either we are missing a mandatory test case, or the existing test cases aren't good enough.
