### ISSUE TITLE
Created files are from root, with root user and group

### ISSUE THREAD

**Issue by hbuerger** [asciidoctor/docker-asciidoctor#57]
If I run the following docker command, all files created are owned by root. Even if executed as user.

docker run --volumes-from taupageapp asciidoctor/docker-asciidoctor asciidoctor --trace -r asciidoctor-diagram -D $WORKSPACE/output $WORKSPACE/docs/index.adoc

If I'm a user e.g. Jenkins, and want to create the documentation, I can run it. The container creates a bunch of files with owner root. After the container terminated, the Jenkins can't delete these files to rerun.

It should be possible to set the user which is used to create the files.

**Comment by dduportal** [comment]
Hello @hbuerger , thanks for taking time to report this issue and giving us context.

Some thoughts over there I would want to share to help:

1. There are some (good) arguments against running containers as root in CI environment: https://batmat.net/2017/01/30/do-not-run-your-tests-in-continuous-integration-with-the-root-user/
2. However, they are some security tricks that could be applied if your challenge is only "ownership of files", which seems the case: https://docs.docker.com/engine/security/userns-remap/ 
3. If you don't want or can't manipulate your Docker Engine configuration (I understand your Jenkins instance could be managed by another team, or you might not have the time now), there is a flag for docker run that will let you switch the default user at runtime: `--user=` (ref. https://docs.docker.com/engine/reference/run/#user where there is a good explanation, you can even pass numerical UID)
4. You can extend the official image to set up a default user (and add it "properly" with its own home shell and name, etc.). Do this if it is worth it (adding the flag would be too much effort across your jobs configurations, and the user is always the same) with a `Dockerfile`, a `RUN` instruction like this one https://github.com/jenkinsci/docker/blob/master/Dockerfile#L18 (official Jenkins image for Docker), and the instruction `USER` (reference: https://docs.docker.com/engine/reference/builder/#user )
5. Another pattern (I personally do this) is to run a 2nd `docker run` command that takes care of the files, that would look like this: `docker run --volumes-from taupageapp asciidoctor/docker-asciidoctor asciidoctor chmod -R 777 $WORKSPACE/output` in your case


To solve your problem:

* Easier is to add the `--user=` and setting it to your Jenkins agent's user UID

However, we (the community) could improve the image by creating a non root user by default and/or improve the documentation.

Tell us here if the `--user=` solution is working for you.

**Comment by mojavelinux** [comment]
I like the idea of creating a non-root user (maybe docs) but not forcing that user to be used by default. In other words, just have the user present in the system. I'd like to know how other containers handle this, though, before making any final decisions. Is there a "standard" user account that is preferred?

**Comment by hbuerger** [comment]
For me the ideal solution would be to pass the starting user into the container, so that the files are owned by the user who started the container. 
I tried the --user option but it failed because the user is not part of the container and the name could not be resolved. But you can use user ids. My Jenkinsfile looks like:

```
...
uid = sh(script : "id -u", returnStdout: true).trim()
gid = sh(script : "id -g", returnStdout: true).trim()
sh "docker run -u ${uid}:${gid} --volumes-from taupageapp asciidoctor/docker-asciidoctor asciidoctor --trace -r asciidoctor-diagram -D $WORKSPACE/output $WORKSPACE/docs/index.adoc"
...
````
This looks like my ideal solution :-)
Thanks for your help.

**Comment by mojavelinux** [comment]
> I tried the --user option but it failed because the user is not part of the container and the name could not be resolved

The question is, should it be? Or in your case, would it not matter since a generic name would not be sufficient anyway?

**Comment by hbuerger** [comment]
As far as I understood docker a new user asciidoctor would get a random UID. Not sure what happens if the user asciidoctor exists on the hosting system.
Another story is security, as far as I know applications should not run as root. But this probably comes from server software. For asciidoctor, starting, processing files, stopping this might not be so important. In a perfect world it would run as user asciidortor preventing overwriting files in the mounted directories which should not be overwritten.

**Comment by mojavelinux** [comment]
My understanding is that a container is a sandbox, so the traditional rules of Unix "don't be root" don't apply. It's more like the whole container is your home directory. But I do agree that that permission should not be (easily) bleeding outside of the container.

**Comment by dduportal** [comment]
Exactly. One of the intent of putting your application in Docker is to make it portable as much as possible, and to "lean" things.
Managing a user (its name, its shell, its home, its uid, its group memberships, etc.) are a pain to maintain and fight against portability.

In the case of containers, the namespacing takes care of isolating your user: the UID 0 "root" of your container is not in the same namespace as your "host" machine's root.
This is the intent of the configuration "user mapping" if you care about security: in this case, docker will even map the "root" of the container to an existing user pre-defined on the host (or created by Docker on the fly), which is not UID 0 on the host.

Be aware that only the UID/GID are counting. The "user" is just a textual representation that can change (UID 1000 set for file mode will map any user with the UID 1000 in different containers).

Functionally speaking, the blog article from @batmat (https://batmat.net/2017/01/30/do-not-run-your-tests-in-continuous-integration-with-the-root-user/) is underlining something outside the security areas: running things as root user might have non wanted behavior.

On the other side, if you set the default user as non root, then you create unwanted complexity: you need to install sudo and configure it (which is not lean...) or have to ask users to add more Dockerfile layers to install package as for the official Jenkins image (Spoiler: I work for CloudBees):
```
FROM jenkinsci/jenkinsci
USER root #Switch as root user
RUN apt-get something
USER jenkins # Switch as jenkins user.
```

@mojavelinux , the official images can be classified on one of the following patterns:

* "Services" that have to run as non root user when running outside Docker, so they run as well with their specific user inside their image:
  - MySQL: https://github.com/docker-library/mysql/blob/883703dfb30d9c197e0059a669c4bb64d55f6e0d/5.7/Dockerfile#L4
  - Redis: https://github.com/docker-library/redis/blob/29b44c477011c5450dd89fd41af4c04e0c71e5b2/4.0/Dockerfile
  - Postgres: https://github.com/docker-library/postgres/blob/1805adb0693d9602bfb19b6bf2583b311c43b749/10/Dockerfile#L15
  - Consul: https://github.com/hashicorp/docker-consul/blob/9fb940c32b6f46b0a77a640d7161054e00e97bbb/0.X/Dockerfile#L16
  - Jenkins (special pattern where the user and UID are specified at build time with a default value): https://github.com/jenkinsci/docker/blob/master/Dockerfile#L5
* "Services" that have to be started as root, and takes care of "restricting" their sub processes children with a restricted user:
  - Nginx: https://github.com/nginxinc/docker-nginx/blob/3ba04e37d8f9ed7709fd30bf4dc6c36554e578ac/mainline/stretch/Dockerfile
  - HTTPD: https://github.com/docker-library/httpd/blob/6d50d7f89f4d8bc6a6a3f86d892e254f4d6bfd8b/2.4/Dockerfile
  - Haproxy: https://github.com/docker-library/haproxy/blob/394255fbe76c57a9f2e0775e3e69df714e801b46/1.7/Dockerfile
* "Command Line" containers, which run on one-shot commands and being run as root to allow easier extensibility and make it "lean":
  - Terraform: https://github.com/hashicorp/docker-hub-images/blob/master/terraform/Dockerfile-full
  - Packer: https://github.com/hashicorp/docker-hub-images/blob/master/packer/Dockerfile-light
  - PowerShell: https://github.com/PowerShell/PowerShell/blob/master/docker/release/fedora26/Dockerfile
* Official Distribution images where default user is root to provide easy customization later

=> The question is "should we see asciidoctor docker image as part of the 3rd category or as the first one"?

My vote is for 3rd category and stay with root to avoid too much complexity.
However, given the use case explained by @hbuerger , writing a few lines with an example with the UID + how to extend the image to set up your own user on a Dockerfile on the README could help.

If we vote to create a user and set it as default, then we need to:
* Find a user name (`asciidoctor` ?)
* Find a User ID to attach to this user with the question: "what if this UID is colliding with any other host".
* Add sudo, manage policies to provide extensibility like installing more packages

@mojavelinux @hbuerger If you agree on the documentation of such thing, I volunteer to write it but I will need review (I'll open a separated issue to keep track of this) :)
