### ISSUE TITLE
asciidoctor-mathematical fonts doesn't work

### ISSUE THREAD

**Issue by mvillafuertem** [asciidoctor/docker-asciidoctor#78]
Hi, 

It appears that some symbols are missing from the fonts.

```
[latexmath,file="tex-formula-2.png"]
++++
\begin{align}
\cup \cap \setminus \subset \subseteq \subsetneq \supset \in \notin \emptyset \varnothing
\end{align}
++++
```

https://math.meta.stackexchange.com/questions/5020/mathjax-basic-tutorial-and-quick-reference

**Comment by dduportal** [comment]
Hello! This issue is fixed by #101. Thanks a lot for reporting!
