### ISSUE TITLE
Code highlighting not working in html

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/docker-asciidoctor#8]
I can't seem to get code highlighting working in html using this.

coderay is installed, but pygmentize on the command line does not work.

Have you tested this? Or could it be an error at my end? Highlighting in PDF does work.

Thanks!

**Comment by gscheibel** [comment]
@plaindocs I'm going to have a look. Thanks for pointing it out.

**Comment by gscheibel** [comment]
@plaindocs I can't reproduce the issue.
here is the document I'm using https://gist.github.com/gscheibel/c4fbbc3c251f9e6269b1
I generate the html (within the container using `asciidoctor test.adoc` ).

Can you give me more information please ? Like document, command, etc.

**Comment by plaindocs** [comment]
Cheers for looking at this.

Your example did work, and helped me track down where I was going wrong:
bash (highlighted with pygments but not coderay, which I knew) BUT my bash did not have anything that triggers the highlighter so it appeared to not work.

Thanks again.
