### ISSUE TITLE
fopub not present

### ISSUE THREAD

**Issue by saxicek** [asciidoctor/docker-asciidoctor#82]
I installed using:
```
docker run -it -v <your directory>:/documents/ asciidoctor/docker-asciidoctor
```
Asciidoctor is there, but fopub not:
```
bash-4.4# asciidoctor -v
Asciidoctor 1.5.8 [https://asciidoctor.org]
Runtime Environment (ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux-musl]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)
bash-4.4# fopub
bash: fopub: command not found
```
Is it not included or am I missing something? Thank you!

**Comment by mojavelinux** [comment]
The Asciidoctor Docker image does not provide fopub. And I don't really want it to because it's not part of the official Asciidoctor "platform". The preferred method of generating a PDF, and the one this image provides, is Asciidoctor PDF (though another option may show up in the near future as we are aware of the limitations of Asciidoctor PDF).

**Comment by saxicek** [comment]
Thank you for the answer. My reason for switching from Asciidoctor PDF to fopub is that my document needs to be printed and it contains many links and footnotes. And I prefer to have both link URLs and footnotes and the bottom of the page and not inlined. And the long standing https://github.com/asciidoctor/asciidoctor-pdf/issues/85 suggests it won't be fixed in the near future unfortunately.

If there are any new options planned I will be glad to try them. Until that it is not a big deal for me to add fopub to your docker image manually. The reason why I raised this is that fopub is explicitly mentioned in this project README. You may want to remove the reference (even though it pointed me to a viable solution of my problem).

**Comment by mojavelinux** [comment]
You are always free to extend this image to add fopub. We are moving away from it as an official part of the stack. Thus, that mention should be removed from the README. Thanks for pointing that out.

**Comment by dduportal** [comment]
Closing this issue given that fopub is not part of the stack anymore.
