### ISSUE TITLE
Repo doesn't have license

### ISSUE THREAD

**Issue by jandersson-svt** [asciidoctor/docker-asciidoctor#86]
This should be a quick one. This repo doesn't have licensee (for the scripts, Dockerfile etc) so please just add one of choice - MIT, Apache 2.0.

**Comment by mojavelinux** [comment]
That's a great point. Technically, it's covered under the umbrella of Asciidoctor (since it's in this organization), which falls back to MIT. If a repository wants a different license, it has to specify one. But I don't see any reason for not to be MIT.
