### ISSUE TITLE
Add asciidoctor-fopub and Java

### ISSUE THREAD

**Issue by plaindocs** [asciidoctor/docker-asciidoctor#9]
Will you accept a pull request to add 

asciidoctor-fopub
java

to the container?

**Comment by gscheibel** [comment]
If you want to generated PDF file, you can use asciidoctor-pdf which is already in the container `asciidoctor-pdf sample.adoc`.

If it's for another purpose may I have the use case please ?

**Comment by plaindocs** [comment]
Yeah, specifically comparing and contrasting the two PDF generators to see which is the most suitable for our purposes. 

I'll probably do it with a2x as well, separately. 

is `asciidoc-pdf` the preferred way? I'm not sure how many of the difference are are from capability, or from config.

**Comment by gscheibel** [comment]
asciidoctor-pdf is the simplest way, because you not rely on docbook and so it avoids potential issues.
Let us know if you find differences.

**Comment by plaindocs** [comment]
There seem to be a *lot* at first glance. I'll see if I can list the obvious ones.
